CupCarbon v. U-One 3.8.2
----------------
name:rega
zoom:0
centerposition_la:41.5508162017373
centerposition_lo:-8.429922759532928
map:0
display_details:false
draw_radio_links:true
draw_sensor_arrows:true
radio_links_color:2
draw_marker_arrows:true
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:false
draw_script_file_name:true
display_print_messages:true
