CupCarbon v. U-One 3.8.2
----------------
name:teste
zoom:1
centerposition_la:41.55112130736882
centerposition_lo:-8.427439033985138
map:0
display_details:true
draw_radio_links:true
draw_sensor_arrows:true
radio_links_color:2
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
